# Generated by Django 4.1.6 on 2023-05-04 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('historia_clinica', '0004_alter_historiaclinica_descripcion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historiaclinica',
            name='descripcion',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='historiaclinicaauditada',
            name='descripcion',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='medico',
            name='matricula',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='medicoauditado',
            name='matricula',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='apellido',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='dni',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='nombre',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='pacienteauditado',
            name='dni',
            field=models.CharField(max_length=20),
        ),
    ]
